//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROMPERU.PERUMODA.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PROMPERU.PERUMODA.Web.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regístrate y accede a.
        /// </summary>
        public static string Access {
            get {
                return ResourceManager.GetString("Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accede a este foro.
        /// </summary>
        public static string Access_Forum {
            get {
                return ResourceManager.GetString("Access_Forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya puedes acceder a la transmisión en vivo.
        /// </summary>
        public static string Access_Now {
            get {
                return ResourceManager.GetString("Access_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regístrate y accede a los ponencias en vivo de Perú Moda &amp; Moda Deco.
        /// </summary>
        public static string Access_Sign_Up {
            get {
                return ResourceManager.GetString("Access_Sign_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acceder al foro.
        /// </summary>
        public static string Access_To {
            get {
                return ResourceManager.GetString("Access_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PerúModa.
        /// </summary>
        public static string APP_NAME {
            get {
                return ResourceManager.GetString("APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regresar.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coorganizadores.
        /// </summary>
        public static string Co_Organizer {
            get {
                return ResourceManager.GetString("Co_Organizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 días de ponencia de moda y deco.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 días de.
        /// </summary>
        public static string Days_30 {
            get {
                return ResourceManager.GetString("Days_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dedicado a moda y deco.
        /// </summary>
        public static string Dedicated {
            get {
                return ResourceManager.GetString("Dedicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorizo a.
        /// </summary>
        public static string Form_Authorize_1 {
            get {
                return ResourceManager.GetString("Form_Authorize_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to poder compartir los datos recabados con terceros, según estime conveniente.
        /// </summary>
        public static string Form_Authorize_2 {
            get {
                return ResourceManager.GetString("Form_Authorize_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono de Contacto.
        /// </summary>
        public static string Form_Contact_Phone {
            get {
                return ResourceManager.GetString("Form_Contact_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string Form_Country {
            get {
                return ResourceManager.GetString("Form_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de documento.
        /// </summary>
        public static string Form_Document_Number {
            get {
                return ResourceManager.GetString("Form_Document_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de documento.
        /// </summary>
        public static string Form_Document_Type {
            get {
                return ResourceManager.GetString("Form_Document_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo Electrónico.
        /// </summary>
        public static string Form_Email {
            get {
                return ResourceManager.GetString("Form_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombres.
        /// </summary>
        public static string Form_First_Name {
            get {
                return ResourceManager.GetString("Form_First_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellidos.
        /// </summary>
        public static string Form_Last_Name {
            get {
                return ResourceManager.GetString("Form_Last_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to campo no obligatorio.
        /// </summary>
        public static string Form_Mandatory {
            get {
                return ResourceManager.GetString("Form_Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Términos y Condiciones.
        /// </summary>
        public static string Form_Privacy {
            get {
                return ResourceManager.GetString("Form_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acepto los.
        /// </summary>
        public static string Form_Privacy_Accept {
            get {
                return ResourceManager.GetString("Form_Privacy_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Región.
        /// </summary>
        public static string Form_Region {
            get {
                return ResourceManager.GetString("Form_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione.
        /// </summary>
        public static string Form_Select {
            get {
                return ResourceManager.GetString("Form_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona un país.
        /// </summary>
        public static string Form_Select_Country {
            get {
                return ResourceManager.GetString("Form_Select_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escoge los bloques de seminarios del que quieres ser parte, puedes marcar más de una opción.
        /// </summary>
        public static string Form_Select_Forums {
            get {
                return ResourceManager.GetString("Form_Select_Forums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione una opción.
        /// </summary>
        public static string Form_Select_Option {
            get {
                return ResourceManager.GetString("Form_Select_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razón Social.
        /// </summary>
        public static string Form_Social {
            get {
                return ResourceManager.GetString("Form_Social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elige la opción con la que te identificas.
        /// </summary>
        public static string Form_User_Type {
            get {
                return ResourceManager.GetString("Form_User_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foro.
        /// </summary>
        public static string Forum {
            get {
                return ResourceManager.GetString("Forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hola.
        /// </summary>
        public static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internacional.
        /// </summary>
        public static string International {
            get {
                return ResourceManager.GetString("International", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conoce el detalle de las más de 60 ponencias que tenemos para ti.
        /// </summary>
        public static string Know {
            get {
                return ResourceManager.GetString("Know", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conoce las tendencias sostenibles que se están desarrollando a nivel mundial y su impacto estratégico en la oferta comercial exportable; teniendo como eje los grandes cambios del consumo debido a la pandemia.
        /// </summary>
        public static string Learn {
            get {
                return ResourceManager.GetString("Learn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ver transmisión en vivo.
        /// </summary>
        public static string Live_Stream {
            get {
                return ResourceManager.GetString("Live_Stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a la transmisión en vivo.
        /// </summary>
        public static string Live_Stream_Soon {
            get {
                return ResourceManager.GetString("Live_Stream_Soon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to un mes de foros.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si aún no te has registrado.
        /// </summary>
        public static string Not_Registered {
            get {
                return ResourceManager.GetString("Not_Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to octubre.
        /// </summary>
        public static string October {
            get {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organiza.
        /// </summary>
        public static string Organize {
            get {
                return ResourceManager.GetString("Organize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cronogramas.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa.
        /// </summary>
        public static string Sign_In {
            get {
                return ResourceManager.GetString("Sign_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regístrate aquí.
        /// </summary>
        public static string Sign_Up {
            get {
                return ResourceManager.GetString("Sign_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si ya te registraste.
        /// </summary>
        public static string Sign_Up_Already {
            get {
                return ResourceManager.GetString("Sign_Up_Already", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regístrate.
        /// </summary>
        public static string Sign_Up_Title {
            get {
                return ResourceManager.GetString("Sign_Up_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regístrate para.
        /// </summary>
        public static string Sign_Up_Title_To {
            get {
                return ResourceManager.GetString("Sign_Up_Title_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pronto podrás ingresar.
        /// </summary>
        public static string Soon {
            get {
                return ResourceManager.GetString("Soon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auspiciadores.
        /// </summary>
        public static string Sponsors {
            get {
                return ResourceManager.GetString("Sponsors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suscríbete para acceder al foro.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suscríbete aquí.
        /// </summary>
        public static string Subscribe_Here {
            get {
                return ResourceManager.GetString("Subscribe_Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡suscripción exitosa!.
        /// </summary>
        public static string Subscribe_Successful {
            get {
                return ResourceManager.GetString("Subscribe_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ponencias.
        /// </summary>
        public static string Talks {
            get {
                return ResourceManager.GetString("Talks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edición Virtual.
        /// </summary>
        public static string Virtual_Edition {
            get {
                return ResourceManager.GetString("Virtual_Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuerda que todas las ponencias son transmitidas mediante Zoom.
        /// </summary>
        public static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
